version: "3"
services:
  app:
    image: account-img:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mongo
      DB_NAME: bank
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - account-network
networks:
  account-network:
    driver: bridge
